// apps/svelte/src/routes/shoes-with-loaders/[slug]/+page.svelte
<script lang="ts">
  import { useQuery } from '@sanity/svelte-loader'
  import type { PageData } from './$types'
  import Shoe from '../../../components/Shoe.svelte'

  export let data: PageData
  const { query, params, options } = data
  const q = useQuery(query, params, options)
  $: ({ data: product, loading } = $q)
</script>

<Shoe {product} {loading} slug={params.slug} />

// apps/next/src/app/shoes/[slug]/page.tsx
import {shoe} from '@/queries'

import {sanityFetch} from '../sanity.live'
import ShoePageClient from './page.client'

type Props = {
  params: Promise<{slug: string}>
}

export default async function ShoePage({params}: Props) {
  const {data: initial} = await sanityFetch({query: shoe, params})

  return <ShoePageClient params={params} initial={initial} />
}
