// apps/nuxt/components/VisualEditing.vue
<template>
  <slot />
</template>

<script lang="ts" setup>
import { studioUrl } from 'apps-common/env'
import {
  type DisableVisualEditing,
  enableVisualEditing,
} from '@sanity/overlays'

let disable: DisableVisualEditing
const router = useRouter()

onMounted(() => {
  disable = enableVisualEditing({
    studioUrl,
    history: {
      subscribe: (navigate) => {
        return router.afterEach((to) => {
          // There is no mechanism to determine navigation type in a Vue Router navigation guard, so just push
          // https://github.com/vuejs/vue-router/issues/1620
          navigate({ type: 'push', url: to.fullPath })
        })
      },
      update: (update) => {
        if (update.type === 'push' || update.type === 'replace') {
          router[update.type](update.url)
        } else if (update.type === 'pop') {
          router.back()
        }
      },
    },
  })
})
onUnmounted(() => disable())
</script>

// apps/next/src/app/shoes/VisualEditing.tsx
'use client'

import { enableVisualEditing, type HistoryUpdate } from '@sanity/overlays'
import { studioUrl } from 'apps-common/env'
import { useEffect, useRef } from 'react'
import { useLiveMode } from './useQuery'
import { usePathname, useSearchParams, useRouter } from 'next/navigation'

export default function VisualEditing() {
  const router = useRouter()
  const navigateComposerRef = useRef<null | ((update: HistoryUpdate) => void)>(
    null,
  )

  useEffect(() => {
    const disable = enableVisualEditing({
      studioUrl,
      history: {
        subscribe: (navigate) => {
          navigateComposerRef.current = navigate
          return () => {
            navigateComposerRef.current = null
          }
        },
        update: (update) => {
          switch (update.type) {
            case 'push':
              return router.push(update.url)
            case 'pop':
              return router.back()
            case 'replace':
              return router.replace(update.url)
            default:
              throw new Error(`Unknown update type: ${update.type}`)
          }
        },
      },
    })
    return () => disable()
  }, [router])

  const pathname = usePathname()
  const searchParams = useSearchParams()
  useEffect(() => {
    if (navigateComposerRef.current) {
      navigateComposerRef.current({
        type: 'push',
        url: `${pathname}${searchParams?.size ? `?${searchParams}` : ''}`,
      })
    }
  }, [pathname, searchParams])

  useLiveMode()

  return null
}
