// apps/nuxt/components/VisualEditing.vue
<template>
  <slot />
</template>

<script lang="ts" setup>
import { studioUrl } from 'apps-common/env'
import { type DisableOverlays, enableOverlays } from '@sanity/overlays'

let disable: DisableOverlays
const router = useRouter()

onMounted(() => {
  disable = enableOverlays({
    studioUrl,
    history: {
      subscribe: (navigate) => {
        return router.afterEach((to) => {
          // There is no mechanism to determine navigation type in a Vue Router navigation guard, so just push
          // https://github.com/vuejs/vue-router/issues/1620
          navigate({ type: 'push', url: to.fullPath })
        })
      },
      update: (update) => {
        if (update.type === 'push' || update.type === 'replace') {
          router[update.type](update.url)
        } else if (update.type === 'pop') {
          router.back()
        }
      },
    },
  })
})
onUnmounted(() => disable())
</script>

// apps/next/src/components/VisualEditing.tsx
import { enableOverlays } from '@sanity/overlays'
import { studioUrl } from 'apps-common/env'
import { useEffect } from 'react'
import { useLiveMode } from './useQuery'
import { useRouter } from 'next/router'

export default function VisualEditing() {
  const router = useRouter()

  useEffect(() => {
    if (!router.isReady) return
    const disable = enableOverlays({
      studioUrl,
      history: {
        subscribe: (navigate) => {
          const handleHistoryChange = (url: string) => {
            navigate({ type: 'push', url })
          }
          router.events.on('beforeHistoryChange', handleHistoryChange)
          return () => {
            router.events.off('beforeHistoryChange', handleHistoryChange)
          }
        },
        update: (update) => {
          switch (update.type) {
            case 'push':
              return router.push(update.url)
            case 'pop':
              return router.back()
            case 'replace':
              return router.replace(update.url)
            default:
              throw new Error(`Unknown update type: ${update.type}`)
          }
        },
      },
    })
    return () => disable()
  }, [
    router.isReady,
    router?.events?.on,
    router?.events?.off,
    router?.push,
    router?.back,
    router?.replace,
  ])

  useLiveMode()

  return null
}
