// apps/remix/app/VisualEditing.tsx
import { useLocation, useNavigate } from '@remix-run/react'
import { enableOverlays, type HistoryAdapterNavigate } from '@sanity/overlays'
import { studioUrl } from 'apps-common/env'
import { useEffect, useRef, useState } from 'react'
import { useLiveMode } from '@sanity/react-loader'
import { client } from '~/sanity'

export default function VisualEditing() {
  const navigateRemix = useNavigate()
  const navigateRemixRef = useRef(navigateRemix)
  const [navigate, setNavigate] = useState<HistoryAdapterNavigate | undefined>()

  useEffect(() => {
    navigateRemixRef.current = navigateRemix
  }, [navigateRemix])
  useEffect(() => {
    const disable = enableOverlays({
      allowStudioOrigin: studioUrl,
      history: {
        subscribe: (navigate) => {
          setNavigate(() => navigate)
          return () => setNavigate(undefined)
        },
        update: (update) => {
          if (update.type === 'push' || update.type === 'replace') {
            navigateRemixRef.current(update.url, {
              replace: update.type === 'replace',
            })
          } else if (update.type === 'pop') {
            navigateRemixRef.current(-1)
          }
        },
      },
    })
    return () => disable()
  }, [])
  const location = useLocation()
  useEffect(() => {
    if (navigate) {
      navigate({
        type: 'push',
        url: `${location.pathname}${location.search}${location.hash}`,
      })
    }
  }, [location.hash, location.pathname, location.search, navigate])

  useLiveMode({ allowStudioOrigin: studioUrl, client })

  return null
}

// apps/svelte/src/components/VisualEditing.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { enableOverlays, type HistoryAdapterNavigate } from '@sanity/overlays'
  import { useLiveMode } from '@sanity/svelte-loader'
  import { afterNavigate, goto } from '$app/navigation'
  import { client } from '$lib/sanity'

  onMount(() => useLiveMode({ client }))

  let navigate: HistoryAdapterNavigate | undefined
  let navigatingFromUpdate = false

  onMount(() =>
    enableOverlays({
      history: {
        subscribe: (_navigate) => {
          navigate = _navigate
          // Initial navigation
          navigate({
            type: 'replace',
            url: window.location.pathname + window.location.search,
          })
          return () => {
            navigate = undefined
          }
        },
        update: (update) => {
          if (update.type === 'push' || update.type === 'replace') {
            navigatingFromUpdate = true
            goto(update.url, { replaceState: update.type === 'replace' })
          } else if (update.type === 'pop') {
            history.back()
          }
        },
      },
    }),
  )

  afterNavigate(async ({ to, complete }) => {
    if (navigate && to && !navigatingFromUpdate) {
      await complete
      navigate({ type: 'push', url: to.url.pathname + to.url.search })
    }
    navigatingFromUpdate = false
  })
</script>
